name: Send Reddit Posts to Telegram (Test)

on:
  workflow_dispatch: # manual run only

jobs:
  reddit-telegram-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python fetch_reddit.py

      - name: Commit updated file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add post_reddit.txt
          git commit -m "Update reddit posts" || echo "No changes to commit"
          git push
