name: Send Reddit Posts to Telegram (Every 10min)

on:
  workflow_dispatch:   # still allows manual runs
  schedule:
    - cron: "*/10 * * * *"   # run every 10 minutes

permissions:
  contents: write

jobs:
  reddit-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python fetch_reddit.py

      - name: Commit updated CSV (if changed)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add posts_reddit.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update reddit posts (CSV)"
            git push
          else
            echo "No changes in CSV, skipping commit"
          fi

      - name: Sync CSV to LFA repo
        run: |
          git clone https://github.com/Jack0fcodes/LFA.git
          cp posts_reddit.csv LFA/posts_reddit.csv
          cd LFA
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts_reddit.csv
          if ! git diff --cached --quiet; then
            git commit -m "Auto-sync CSV from redd0tBot"
            git push https://x-access-token:${{ secrets.LFA_TOKEN }}@github.com/Jack0fcodes/LFA.git main
          else
            echo "No changes to sync, skipping push"
          fi
