name: Send Reddit Posts to Telegram (Auto)

off:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:      # allow manual trigger too

jobs:
  reddit-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      # Restore cached sent_posts.txt
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: sent_posts.txt
          key: reddit-sent-posts

      - name: Run script
        run: python fetch_reddit.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
